### ISSUE TITLE
Feature: Sign in as staff with code

### ISSUE THREAD

**Issue by dennishilgert** [herr-ober/backend#16]
### Description / Problem
- As an event staff member I want to be able to join existing events with a code of the organizer, so that I can help in my role at the event.

### Solution
Implement the following API Endpoints:
- POST /api/staff/login
{ code: string } --> { token: string }

**Comment by Angmar3019** [comment]
- Could it be that the API endpoint should be set to this address?

  POST /api/staff/login
  { code: string } --> { token: string }
  
  The endpoint `/api/events/login` given by the issue doesn't work.

- I get a "500 Internal Server Error" message with "Failed to authenticate by staff code" if I try to get a token.
  
  I used the endpoint `/api/events/staff/login` with the request `{
	  "code": "D5Y4Zptf"
  }`
